apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notes
  name: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  strategy: {}
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - image:  s160621/django_app:latest
        name:  notes
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
